server:
  port: 8080
spring:
  application:
    name: admin
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://172.19.80.206:3305/test?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#    username: dialog
#    password: dialog
    url: jdbc:mysql://127.0.0.1:3306/admin?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
  freemarker:
    suffix: .html
    settings:
      classic_compatible: true
  jackson:
    #    property-naming-strategy: SNAKE_CASE
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    locale: zh_CN
    time-zone: GMT+8
  profiles:
    include: system

logging:
  level:
    com.chanpion.admin.system.dao: debug

mybatis:
  type-aliases-package: com.chanpion.admin.system.entity
  mapper-locations: classpath:mybatis/*.xml
  configuration:
    map-underscore-to-camel-case: true
